name: "Deploy step simple workflow" 
on:
  push: 
    branches: 
    - deploy
jobs:
  basic-deployment: 
    runs-on: self-hosted
    steps: 
      - name: Checkout the repo
        uses: actions/checkout@v6

      - name: Log in to docker hub
        run: sudo docker login -u  ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        run: sudo docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/simple-app-basic" .

      - name: Push
        run: sudo docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-app-basic

      - name: Run
        run: |
          sudo docker stop simple-app-basic || true
          sudo docker rm simple-app-basic || true
          sudo docker run -d -p 80:80 --name simple-app-basic ${{ secrets.DOCKERHUB_USERNAME }}/simple-app-basic:latest
          


      

